name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 and execute commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }} #nuesatra ip o dominio si tenemos ssl
          username: ${{ secrets.EC2_USERNAME }} # ubuntu es nuestro usuario
          key: ${{ secrets.EC2_PRIVATE_KEY }} #nuestro archivo .pem
          script: |
            cd /var/www/html
            sudo rm -rf html
            sudo mkdir html
            cd html
            sudo git clone https://github.com/joropge/prueba_git_actions .
            sudo systemctl restart nginx